# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish All Projects
      run: |
        for project in $(find ./Src -name "*.csproj"); do
            project_name=$(basename "$project" .csproj)
        
            # Check if the project name is one of the ones we want to publish
            if [[ "$project_name" == "dyno-wasm" || "$project_name" == "dyno-api" || "$project_name" == "dyno-server" ]]; then
                echo "Publishing $project_name ($project)"
                dotnet publish "$project" --configuration Release --output ./publish/"$project_name"
            else
                echo "Skipping $project_name"
            fi
        done
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: dyno-output  # The name of the artifact
        path: ./publish
