name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master  # Deploy on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Install SSH agent
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Deploy files to Raspberry Pi
    - name: Copy files to Raspberry Pi
      run: |
        scp -r ./ pi@${{ secrets.SSH_HOST }}:/home/pi/apps/dyno

    # Run commands on Raspberry Pi (optional)
    - name: Run deployment commands on Raspberry Pi
      run: |
        ssh pi@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/pi/apps/dyno
          dotnet build
          dotnet run dyno-server.csproj
        EOF
